<?php
/**
 * Get an array of mxCalendar events - retrieved from database together with generated on-the-fly.
 *
 * @var $modx modX
 * @var $scriptProperties array
 *
 * @var $criteria xPDOQuery
 * @var $debug bool
 *
 * @return array(
 *   'events',      // unsorted array of events (retrieved from database together with generated by repeat template)
 *   'debugOutput', // string, containing information, valuable for debugging
 * )
 */
/** @var $mxCal mxCalendars */
$mxCal = $modx->runSnippet('mxCalendar.init', $scriptProperties);

$debugOutput = '';
$debug = $modx->getOption('debug', $scriptProperties);
$criteria = $modx->getOption('criteria', $scriptProperties, $modx->newQuery('mxCalendarEvents')->select(array(
	'mxCalendarEvents.*',
)));
$criteria->prepare();
if($debug) $debugOutput .= '<br /><br />Filtering calendar date SQL range with: '.strftime('%m/%d/%Y', $elStartDate).' through '.strftime('%m/%d/%Y', $elEndDate).'<br /><br />';
if($debug) $debugOutput .= 'SQL: '.$criteria->toSql().'<br /><br />';
$queryTimer = new makeProcessTime(null,$debug);
$mxcalendars = $modx->getCollection('mxCalendarEvents',$criteria);
$queryTimer->end('mxCalendars Query');
if($debug) $debugOutput .= "<br />Returned Events: ".count($mxcalendars).'<br />';
$resultLoopTimer = new makeProcessTime(null,$debug);
$arrEventDates = array();
/** @var $mxc mxCalendarEvents */
foreach ($mxcalendars as $mxc) {
	//-- Convert the object to an array
	$mxcArray = $mxc->toArray();

	$eStart    = new DateTime(date('Y-m-d H:i:s',$mxc->get('startdate')));
	$eEnd      = new DateTime(date('Y-m-d H:i:s',$mxc->get('enddate')));

	$isNew = (version_compare(PHP_VERSION, '5.3.0') >= 0);
	$diff = $isNew ? $eStart->diff($eEnd) : (object)$mxCal->datediff($mxc->get('startdate'),$mxc->get('enddate'),true);
	$durYear = $isNew ? $diff->format('%y') : $diff->years;
	$durMonth = $isNew ? $diff->format('%m') : $diff->months;
	$durDay = $isNew ? $diff->format('%d') : $diff->days;
	$durHour = $isNew ? $diff->format('%h') : $diff->hours;
	$durMin = $isNew ? $diff->format('%i') : $diff->minutes;
	$durSec = $isNew ? $diff->format('%s') : $diff->seconds;

	//-- return event duration values
	$mxcArray['durYear']        = !empty($durYear) ? $durYear : null;
	$mxcArray['durMonth']       = !empty($durMonth) ? $durMonth : null;
	$mxcArray['durDay']         = !empty($durDay) ? $durDay : null;
	$mxcArray['durHour']        = !empty($durHour) ? $durHour : null;
	$mxcArray['durMin']         = !empty($durMin) ? $durMin : null;
	$mxcArray['durSec']         = !empty($durSec) ? $durSec : null;
	$mxcArray['mxcmodalClass']  = ($modalView && $ajaxResourceId || isset($_REQUEST['imajax']) ? 'mxcmodal' : '');

	$arrEventsDetail[$mxcArray['id']] = $mxcArray;
	$arrEventDates[$mxcArray['id']] = array(
		'date'=>$mxcArray['startdate'],
		'eventId'=>$mxcArray['id'],
		'repeatId'=>0,
	);

	//-- If we have repeating dates and repeating is enabled lets add those to the array
	if ($mxcArray['repeating'] && ($repeatDates = explode(',', $mxcArray['repeatdates']))) {
		if($debug) $debugOutput .= 'Repeating Event: '.$mxcArray['title'].'<br />';
		if($debug) $debugOutput .= '&nbsp;&nbsp;&nbsp;++(0)&nbsp;&nbsp;'.strftime($dateFormat.' '.$timeFormat, $mxcArray['startdate']).'<br>';
		$rid = 1;
		foreach ($repeatDates AS $rDate) {
			if (empty($rDate)) {
				continue;
			}
			$arrEventDates[$mxcArray['id'].'-'.$rid] = array(
				'date'=>$rDate,
				'eventId'=>$mxcArray['id'],
				'repeatId'=>$rid,
			);
			if($debug) $debugOutput .= '&nbsp;&nbsp;&nbsp;++('.$rid.')&nbsp;&nbsp;'.strftime($dateFormat.' '.$timeFormat, $rDate).'<br>';
			$rid++;
		}
	}

	// Add date for each day in a multiple day event ( #127 )
	if($mxcArray['durDay'] !== null && $mxcArray['durDay'] >= 1){
		if($debug) $debugOutput .= 'Multiple Day Event: '.$mxcArray['title'].'<br />';

		/*
		$i = 1;
		$endDate = $mxc->get('enddate');
		while(strtotime('+'.$i.' day', $mxcArray['startdate']) < $endDate){
			$theSpanDate = strtotime('+'.$i.' day', $mxcArray['startdate']);
			$arrEventDates[$mxcArray['id'].'_'.$i] = array('date'=>$theSpanDate, 'eventId'=>$mxcArray['id'],'repeatId'=>null);
			if($debug) $debugOutput .= '&nbsp;&nbsp;&nbsp;++('.$i.')&nbsp;&nbsp;'.strftime($dateFormat.' '.$timeFormat, $theSpanDate).'<br>';
			$i++;
		}
		 *
		 */

		for ($i = 1; $i<=$mxcArray['durDay']; $i++) {
			$theSpanDate = strtotime('+'.$i.' day', $mxcArray['startdate']);
			$arrEventDates[$mxcArray['id'].'_'.$i] = array(
				'date'=>$theSpanDate,
				'eventId'=>$mxcArray['id'],
				'repeatId'=>null,
			);
			if($debug) $debugOutput .= '&nbsp;&nbsp;&nbsp;++('.$i.')&nbsp;&nbsp;'.strftime($dateFormat.' '.$timeFormat, $theSpanDate).'<br>';
		}
	}

	//$output .= $mxCal->getChunk($tpl,$mxcArray);
}
$resultLoopTimer->end('mxc result set loop');

// Indexed array - in order to be used with list().
return array($arrEventDates,$debugOutput);